### ISSUE TITLE
some errors...here

### ISSUE THREAD

**Issue by moebiussurfing** [c-mendoza/ofxRemoteParameters#1]
hey @c-mendoza ,
thanks for sharing.
I tested a bit fast... and sorry to ask this before a deeper test,

Are your dependencies forks already updated to this? Is this ready to use? (ofxRemoteParameters and ofxParameterServer)
What is the simplest combination of server/client to test it? 

I build the examples/syncParameters and examples/basic_server
But I had to make some modifications and I am not sure if am doing well.

EDIT:
when finally both compiled I don't see the gui parameters or drawing radius are linked...

```
syncParameters/src/ofApp.h
- #include "ofxParameterServer.h"
+ #include "ofxParameterServer.hpp" 
```
on ofxParameterServer.hpp, I needed to "declare" the function adding {}, bc do not where declared into cpp.
void syncParametres() { };

on ofxRemoteParameters/blob/main/examples/of_client/src/ofxParameterClient.h
setup method didn't have the ending " ; "...
```setup(std::string serverAddress, int serverInPort, int serverOutPort)```

Also to add ofxOsc manually to the addons.make files...

I saw started the repo to a web/fluke client... So maybe your are working on this yet, and we must wait a bit.

Thanks again for your work, and sorry for the fast questions.
(I checked this on Windows and macOS)

**Comment by c-mendoza** [comment]
Yikes, I uploaded the wrong example files to the repo ¯\_(ツ)_/¯

It should be fixed now. Can you update your clone and try again?

**Comment by moebiussurfing** [comment]
hey,
I tried to compile on Windows the \ofxRemoteParameters\examples\basic_server, 
(I had to delete from the project the files Makefile and config.make, to avoid PG errors.)
Then I get these errors on VS2017:

```.bash 
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0029	expected an expression	basic_server	F:\openFrameworks\addons\ofxRemoteParameters\src\ofxRemoteParameters\Server.cpp	81	
Error (active)	E0029	expected an expression	basic_server	F:\openFrameworks\addons\ofxRemoteParameters\src\ofxRemoteParameters\Server.cpp	81	
Error	C2059	syntax error: '.'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	81	
Error	C2143	syntax error: missing ';' before '}'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	81	
Error	C2059	syntax error: '}'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	81	
Error	C2059	syntax error: ')'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	81	
Error	C2059	syntax error: '}'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	83	
Error	C2143	syntax error: missing ';' before '}'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	83	
Error	C2143	syntax error: missing ';' before '{'	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	86	
Error	C2447	'{': missing function header (old-style formal list?)	basic_server	f:\openframeworks\addons\ofxremoteparameters\src\ofxremoteparameters\server.cpp	86	
```

![Capture1](https://user-images.githubusercontent.com/2106149/111711728-20313880-882b-11eb-9159-54f49b7501b9.JPG)

On \ofxRemoteParameters\examples\of_client I get the same errors.

I'll report also it in macOS when I tried on there.

**Comment by c-mendoza** [comment]
I don't have MSVC to test but I made a change that might get rid of that error. Can you try it on your end?

**Comment by moebiussurfing** [comment]
thanks @c-mendoza ,
now it compiled well both apps.

But client is not building the GUI, and do not connect to the client app...

I changed the client to localhost:
const static std::string SERVER_IP_ADDRESS = "127.0.0.1";
I also added the ports on server setup (just in case. Flipped in/out too...):
```
//paramServer.setup(mainGroup);
paramServer.setup(mainGroup, 12000, 12001);
```
When I click on "connect" button nothing happens, params are not listed and GUI group looks empty...

Any tip about?

**Comment by c-mendoza** [comment]
Are both ‘basic_server’ and ‘of_client’ running? What is the console output for each?

**Comment by moebiussurfing** [comment]
yes, sure. both apps running, and not any messages output in the console...
neither when clicking "connect"

**Comment by c-mendoza** [comment]
Finally installed Visual Studio and there was a silly bug in my code that only happens on Windows. Give it another try now.

**Comment by moebiussurfing** [comment]
nice! I'll test soon on Windows. Today I compiled in macOS 10.12 and it works.

**Comment by moebiussurfing** [comment]
hey @c-mendoza , It worked perfectly on VS2017 / Windows. Thanks a lot for your fixes!

PS:

I just made a test integrating the use of your ofxRemoteParameters with my ofxPresetsManager add-on.
I have seen that you made the other parameters add-ons, and maybe you could take a look into this one.
Could be useful for you, maybe.

With some little lines, you can add your parameters to your client example to have a presets engine. something like:
```.c++
#include "ofxPresetsManager.h"
ofxPresetsManager presetsManager;

//--------------------------------------------------------------
void ofApp::buildGui()
{
	presetsManager.clear();
	presetsManager.add(params, { '0', '1', '2', '3', '4', '5' });
	presetsManager.setup();
}
```
https://github.com/moebiussurfing/ofxPresetsManager/tree/master/3A_example-LinkServer/src
https://github.com/moebiussurfing/ofxPresetsManager/tree/master/3B_example-LinkClient/src

From the addon README:
*This allows you to control the presets on the Client OF_APP.
The Server OF_APP draws your scene using the linked/received parameters from the Client OF_APP.
This is useful because in some scenarios could help improve the performance or the compiling time and dependencies.
(Because we split in two apps: control + render)*

**Comment by moebiussurfing** [comment]
https://github.com/moebiussurfing/ofxPresetsManager

**Comment by moebiussurfing** [comment]
[VIDEO](https://www.youtube.com/watch?v=kV-t8lIdNRg)

**Comment by moebiussurfing** [comment]
![Capture_v2](https://user-images.githubusercontent.com/2106149/112278459-9dacdc80-8c61-11eb-8623-6a9bf726eca7.JPG)
