### ISSUE TITLE
[question] approach to use with a vector of colors...

### ISSUE THREAD

**Issue by moebiussurfing** [c-mendoza/ofxRemoteParameters#3]
I want to sync two apps with a (variable size) vector<ofColor>. 
similar to current examples.

Do you think I could use 
ofxParameterCollection<ofColor> positionsCollection;
?

Or do you think there's a simpler approach doing a de/serializer like you explain on the readme:
```
Thus, the general approach is:
inline std::ostream& operator<<(std::ostream& os, const customType& instance)
{
	os << [[some function that turns instance into a string]]
	return os;
}
inline std::istream& operator>>(std::istream& is, customType& instance)
{
  ... (get values from the stream and assign them to your instance)
	return is;
}
```

Do you think it's a good idea to use your add-on for this?

thanks, @c-mendoza

**Comment by c-mendoza** [comment]
I just tested ofxParameterCollection with ofxRemoteParameters and it works just fine, so yes, give it a shot. The only thing is that on the server, when you add or remove from the collection, you need to call:

`myServer.syncParameters()`

That updates the "model" in the server and sends it to the client.

So in the ofxParameterCollection example, you would add:

In ofApp.h:

`ofxRemoteParameters::Server server;`

In ofApp.cpp:

```c++
void ofApp::setup(){
        ...
        ...
        server.setup(mainGroup);
}
void ofApp::buildGui() {
	gui.clear();
	gui.add(&addCircleButtton);
	gui.add(&removeLastCircleButton);
	gui.add(&removeRandomButton);
	gui.add(mainGroup);

	server.syncParameters();
}
```
